# Generated by Django 5.2.6 on 2025-09-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
