# Generated by Django 5.2.6 on 2025-09-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_missingproduct_quantity_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='price',
        ),
    ]
