# Generated by Django 5.2.6 on 2025-09-17 05:26

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_unit_price_product_price'),
    ]

    operations = [
            migrations.AddField(
                model_name='product',
                name='unit_price',
                field=models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0),
        ),
    ]
